name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  create_wheel_and_sdist:
    name: create_wheel_and_sdist
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: [ create_wheel_and_sdist ]
    runs-on: ubuntu-latest
    
    environment: pypi
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for Trusted Publishing

    steps:
      - uses: actions/checkout@v7

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: Package-Distributions-construct-editor
          path: ./dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1